// @ts-nocheck
// tauri-specta 생성물. 손으로 고치지 말 것 — cargo test가 다시 만든다.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async appInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("app_info");
},
/**
 * 프리셋 목록. 설정 폼의 드롭다운을 채운다.
 */
async jiraPresets() : Promise<Preset[]> {
    return await TAURI_INVOKE("jira_presets");
},
/**
 * Jira 연결이 설정돼 있는가. 설정 안내를 띄울지 결정한다.
 */
async jiraIsConfigured() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_is_configured") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 설정창의 "연결 테스트" 버튼.
 */
async jiraVerify(baseUrl: string, email: string, apiToken: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_verify", { baseUrl, email, apiToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 자격증명 저장. 토큰과 이메일은 키체인, base_url만 파일.
 */
async jiraSaveCredentials(baseUrl: string, email: string, apiToken: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_save_credentials", { baseUrl, email, apiToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 위젯 하나의 데이터를 가져온다.
 * 
 * 흐름: 캐시 즉시 반환이 아니라 **네트워크 시도 → 실패 시 캐시로 폴백**.
 * 앱 시작 시의 0ms 표시는 별도 커맨드([`jira_cached`])가 담당한다 —
 * 두 경로를 나눠야 프론트가 "캐시부터 그리고 갱신" 순서를 제어할 수 있다.
 */
async jiraFetch(widgetId: string, config: JiraWidgetConfig) : Promise<Result<JiraWidgetData, JiraWidgetError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_fetch", { widgetId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 디스크 캐시만 읽는다. 네트워크를 건드리지 않으므로 즉시 반환된다.
 * 
 * **앱 시작 시 이것을 먼저 부른다.** 0ms에 실제 데이터를 그리는 것이
 * Jira 웹과의 결정적 차이(DECISIONS 17장).
 */
async jiraCached(widgetId: string) : Promise<Result<JiraWidgetData | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_cached", { widgetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardLoad() : Promise<Result<BoardFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_load") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardSave(file: BoardFile) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_save", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppInfo = { version: string; 
/**
 * 유휴 메모리 목표 150MB 대비 실측치를 설정창에 노출하기 위한 자리.
 * 실제 측정은 후속 작업.
 */
memory_bytes: number | null }
export type Board = { id: string; name: string; widgets?: Widget[] }
export type BoardFile = { version: number; activeBoardId: string; boards: Board[] }
/**
 * 목록 위젯 행 하나. **여기 필드를 늘리기 전에 [`LIST_FIELDS`]와 페이로드 크기를 생각할 것.**
 * 
 * `Deserialize`는 파일 아래쪽에 손으로 구현했다 — Jira의 `{key, fields:{...}}` 중첩을
 * 평평하게 펴고 `avatarUrls` 맵을 URL 하나로 접어야 하기 때문.
 */
export type JiraIssue = { 
/**
 * `PROJ-123`. 사용자에게 보이는 유일한 식별자이자 우리 캐시 키.
 */
key: string; summary: string; status: JiraStatus | null; 
/**
 * 담당자 없음은 흔하다. 백로그 티켓 대부분이 그렇다.
 */
assignee: JiraUser | null; 
/**
 * 우선순위 스킴을 끈 프로젝트에서는 null.
 */
priority: JiraPriority | null; issueType: JiraIssueType | null; 
/**
 * ISO 8601 + 오프셋 (`2026-07-29T14:03:11.482+0900`). 기본 정렬 축.
 */
updated: string | null }
export type JiraIssueType = { name: string; iconUrl?: string | null; subtask?: boolean }
export type JiraPriority = { name: string; iconUrl?: string | null }
/**
 * 위젯 config에 저장되는 쿼리. 프리셋이거나 생 JQL이거나 둘 중 하나.
 * 
 * 프리셋을 JQL 문자열로 굳혀 저장하지 않는 이유: 나중에 프리셋 정의를 고치면
 * 이미 배치된 위젯들도 같이 고쳐져야 한다. id로 저장하면 그게 공짜다.
 */
export type JiraQuery = 
/**
 * 프리셋 id. 알 수 없는 id면 [`JiraQuery::to_jql`]가 `None`을 준다.
 */
{ kind: "preset"; id: string } | 
/**
 * 탈출구. 사용자가 직접 쓴 JQL을 **그대로** 보낸다.
 * 
 * 검증하지 않는다 — 우리가 JQL 파서를 쓸 이유가 없고, 틀리면 Jira가
 * 훨씬 나은 에러 메시지를 준다 (DECISIONS 16장, 400은 원문 보존).
 */
{ kind: "raw"; jql: string }
export type JiraStatus = { name: string; 
/**
 * 워크플로우가 이상하게 설정된 프로젝트에서 누락될 수 있다.
 */
statusCategory?: JiraStatusCategory | null }
/**
 * 상태 카테고리. 색을 칠하는 근거는 상태 **이름**이 아니라 이것이다.
 * 
 * 상태 이름은 프로젝트마다 다르다("완료"/"Done"/"배포됨"). `statusCategory.key`는
 * `new` / `indeterminate` / `done` 세 가지로 고정이라 위젯이 믿을 수 있는 유일한 축이다.
 */
export type JiraStatusCategory = { 
/**
 * `new` | `indeterminate` | `done` (Jira가 보장하는 고정 키)
 */
key: string; 
/**
 * `blue-gray` | `yellow` | `green` — 표시용 힌트
 */
colorName?: string | null; name?: string | null }
/**
 * 사용자. 식별자는 **`accountId`** — 이메일/username이 아니다 (GDPR 이후 Cloud 정책).
 */
export type JiraUser = { accountId: string; 
/**
 * 드물게 비어 있다(비활성/삭제된 계정). 그래도 항상 문자열은 온다.
 */
displayName?: string; 
/**
 * 48x48 아바타 URL. 아바타가 없는 계정이 실제로 있다.
 */
avatarUrl?: string | null }
export type JiraWidgetConfig = { query: JiraQuery; 
/**
 * DECISIONS 11.2 — 기본 30건.
 */
maxResults: number }
/**
 * 위젯 데이터 봉투. 프론트의 `WidgetEnvelope<T>`와 짝을 이룬다.
 * 
 * 로딩/에러 상태를 명시적으로 담는 이유: TanStack Query를 쓰지 않기로 했으므로
 * (DECISIONS 5장) 그것이 공짜로 주던 `isLoading`/`isError`를 직접 모델링해야 한다.
 */
export type JiraWidgetData = { issues: JiraIssue[]; 
/**
 * 실제로 네트워크에서 가져온 시각. 캐시 히트면 과거 시각이다 — "N분 전 데이터" 표시용.
 */
fetchedAt: string; 
/**
 * 이 응답이 디스크 캐시에서 왔는가. true면 갱신이 실패했거나 아직 안 끝났다는 뜻.
 */
fromCache: boolean }
export type JiraWidgetError = { 
/**
 * `transient` | `permanent` — 프론트가 재시도 UI를 고르는 축.
 */
kind: string; message: string; 
/**
 * 401 여부. 전역 배너를 한 번만 띄우기 위한 신호(DECISIONS 16장).
 */
isAuthFailure: boolean; retryAfterSecs: number | null; 
/**
 * 실패했지만 직전 성공 데이터가 있으면 함께 준다. 목록을 비우지 않기 위해서.
 */
stale: JiraWidgetData | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * 프리셋 정의. 정적 테이블이므로 `&'static str`.
 */
export type Preset = { 
/**
 * 저장되는 안정적 식별자. **한번 정하면 바꾸지 않는다** (기존 위젯이 깨진다).
 */
id: string; 
/**
 * 설정 UI에 보이는 이름.
 */
name: string; 
/**
 * 이 프리셋이 무엇을 보여주는지 한 줄 설명.
 */
description: string; jql: string }
export type Widget = { id: string; type: WidgetType; layout: WidgetLayout; 
/**
 * Type-specific settings — JQL, GitHub query, refresh interval, and so on.
 * 
 * Deliberately untyped. DECISIONS 4: 위젯 하나 = 프론트 폴더 하나 + Rust
 * provider 하나. If this module named every provider's config type, adding
 * a widget would mean editing storage, which is exactly the coupling the
 * decision forbids. Providers own their own shapes and parse this
 * themselves.
 */
config?: JsonValue }
/**
 * Grid position. DECISIONS 2: 12-column grid, so `x + w <= 12`.
 * 
 * Not enforced here — react-grid-layout owns collision and compaction, and a
 * store that rejected layouts RGL considers valid would fight it.
 */
export type WidgetLayout = { x: number; y: number; w: number; h: number }
/**
 * Widget type. DECISIONS 3 caps instances per type, not overall — Todo widgets
 * are free while Jira widgets cost API quota.
 */
export type WidgetType = "jira" | "github" | "todo"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
