// @ts-nocheck
// tauri-specta 생성물. 손으로 고치지 말 것 — cargo test가 다시 만든다.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async appInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("app_info");
},
/**
 * 프리셋 목록. 설정 폼의 드롭다운을 채운다.
 */
async jiraPresets() : Promise<Preset[]> {
    return await TAURI_INVOKE("jira_presets");
},
/**
 * 프로젝트 목록. 위젯 설정의 범위 선택을 채운다.
 */
async jiraProjects() : Promise<Result<JiraProject[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Jira 연결이 설정돼 있는가. 설정 안내를 띄울지 결정한다.
 */
async jiraIsConfigured() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_is_configured") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async jiraConnection() : Promise<Result<JiraConnectionInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_connection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 설정창의 "연결 테스트" 버튼.
 */
async jiraVerify(baseUrl: string, email: string, apiToken: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_verify", { baseUrl, email, apiToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 자격증명 저장. 토큰과 이메일은 키체인, base_url만 파일.
 */
async jiraSaveCredentials(baseUrl: string, email: string, apiToken: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_save_credentials", { baseUrl, email, apiToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 위젯 하나의 데이터를 가져온다.
 * 
 * 흐름: 캐시 즉시 반환이 아니라 **네트워크 시도 → 실패 시 캐시로 폴백**.
 * 앱 시작 시의 0ms 표시는 별도 커맨드([`jira_cached`])가 담당한다 —
 * 두 경로를 나눠야 프론트가 "캐시부터 그리고 갱신" 순서를 제어할 수 있다.
 */
async jiraFetch(widgetId: string, config: JiraWidgetConfig) : Promise<Result<JiraWidgetData, JiraWidgetError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_fetch", { widgetId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 디스크 캐시만 읽는다. 네트워크를 건드리지 않으므로 즉시 반환된다.
 * 
 * **앱 시작 시 이것을 먼저 부른다.** 0ms에 실제 데이터를 그리는 것이
 * Jira 웹과의 결정적 차이(DECISIONS 17장).
 */
async jiraCached(widgetId: string) : Promise<Result<JiraWidgetData | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_cached", { widgetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 티켓 하나의 상세. **캐시하지 않는다** (D2) — 목록이 준 골격 위에 덧그리는 값이라
 * 낡은 것을 보여줄 바에는 잠깐 비어 있는 편이 정직하다.
 */
async jiraIssue(key: string) : Promise<Result<JiraIssueDetail, JiraCallError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_issue", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 코멘트 최신 20건을 대화 순서로 (D3).
 */
async jiraComments(key: string) : Promise<Result<JiraCommentsView, JiraCallError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_comments", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 프로젝트 + 이슈타입. 디스크 캐시가 있으면 네트워크를 건드리지 않는다 (D9).
 */
async jiraCreateOptions(forceRefresh: boolean) : Promise<Result<JiraCreateOptions, JiraCallError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_create_options", { forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 생성 폼 스키마. 세션 캐시 히트면 네트워크를 건드리지 않는다 (D10).
 */
async jiraCreatemeta(projectKey: string, issueTypeId: string, forceRefresh: boolean) : Promise<Result<CreateMeta, JiraCallError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_createmeta", { projectKey, issueTypeId, forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 내 계정. "나에게 할당" 체크박스가 쓴다. 세션 캐시.
 */
async jiraMyself() : Promise<Result<JiraIdentity, JiraCallError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_myself") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 티켓 생성. 우리가 하는 유일한 쓰기 (DECISIONS 11.5).
 * 
 * 실패 처리는 5.6의 결정 트리를 그대로 따른다. 핵심은 **400 계열만 자동 재시도**한다는 것.
 * 네트워크·타임아웃·5xx는 요청이 닿았는지 알 수 없으므로 재시도하면 티켓이 두 개가 되고,
 * 우리에겐 지우는 기능이 없다.
 */
async jiraCreateIssue(input: CreateIssueInput) : Promise<Result<CreatedIssue, JiraCreateFailure>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jira_create_issue", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async todoList() : Promise<Result<TodoItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("todo_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 항목 추가. id는 **Rust가 만든다** — 생성 규칙이 한 곳에 있어야 한다.
 */
async todoAdd(text: string, date: string) : Promise<Result<TodoItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("todo_add", { text, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async todoSetDone(id: string, done: boolean) : Promise<Result<TodoItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("todo_set_done", { id, done }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 텍스트 수정. 프론트는 Enter/blur에서만 부른다 — 글자마다 디스크를 때리지 않는다.
 */
async todoSetText(id: string, text: string) : Promise<Result<TodoItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("todo_set_text", { id, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 삭제. **사용자가 명시적으로 요청했을 때만** 호출된다 (DECISIONS 13: 자동 삭제 금지).
 */
async todoRemove(id: string) : Promise<Result<TodoItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("todo_remove", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 과거의 미완료 항목을 `today`로 옮긴다.
 * 
 * `today`를 프론트가 넘기는 이유: 자정 넘김 감지와 "과거를 보는 중에는 미룬다"는
 * 판단이 전부 UI 조건이다(`todos.rs`의 `carry_over` 주석). Rust는 시계를 모른다.
 * 
 * 멱등이다 — 이월 직후 다시 불러도 빈 report가 온다. 앱 시작과 자정 감지가
 * 몇 초 차이로 겹쳐도 안전한 이유다.
 */
async todoCarryOver(today: string) : Promise<Result<CarryOverResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("todo_carry_over", { today }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async todoUndoCarryOver(report: CarryOverReport) : Promise<Result<UndoCarryResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("todo_undo_carry_over", { report }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardLoad() : Promise<Result<BoardFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_load") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardSave(file: BoardFile) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_save", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * `allowedValues` 항목. Jira는 필드 종류마다 다른 모양을 주므로
 * 공통분모(id/value/name)만 뽑고 원본은 `raw`로 남긴다.
 */
export type AllowedValue = { id: string | null; 
/**
 * 화면에 보일 문자열. `name` → `value` → `id` 순으로 찾는다.
 */
label: string | null }
export type AppInfo = { version: string; 
/**
 * 유휴 메모리 목표 150MB 대비 실측치를 설정창에 노출하기 위한 자리.
 * 실제 측정은 후속 작업.
 */
memory_bytes: number | null }
export type Board = { id: string; name: string; widgets?: Widget[] }
export type BoardFile = { version: number; activeBoardId: string; boards: Board[] }
/**
 * One item's before-state, enough to put it back.
 */
export type CarriedItem = { id: string; 
/**
 * The date it was on before the sweep.
 */
fromDate: string; 
/**
 * The date it landed on (always the `today` passed to the sweep).
 */
toDate: string; 
/**
 * `carried_count` before the increment.
 */
previousCarriedCount: number }
/**
 * Result of a carry-over sweep.
 * 
 * DECISIONS 13: 자동 실행 + 되돌리기 가능. This carries enough state for the
 * caller to offer an undo, and to decide whether to say anything at all.
 */
export type CarryOverReport = { carried: CarriedItem[]; 
/**
 * Distinct source dates the items came from, ascending. Lets the UI say
 * "3일치 항목을 가져왔습니다" after a weekend.
 */
sourceDates: string[]; targetDate: string }
/**
 * 이월 결과 + 갱신된 전체 목록.
 * 
 * 둘을 함께 주는 이유: 프론트가 목록을 다시 요청하는 왕복을 없애고,
 * 배너("3개를 가져왔습니다")와 목록이 **같은 시점의 상태**임을 보장한다.
 */
export type CarryOverResult = { items: TodoItem[]; report: CarryOverReport }
/**
 * 티켓 생성 요청. 최소 폼 + createmeta로 알아낸 추가 필드 (DECISIONS 11.3).
 * 
 * `extra_fields`가 있는 이유: 프로젝트마다 필수 필드가 다르므로(XYZ의 `reporter`)
 * 컴파일 타임에 필드 목록을 고정할 수 없다.
 */
export type CreateIssueInput = { 
/**
 * 프로젝트 키 (`ABC`, `XYZ`, …)
 */
projectKey: string; 
/**
 * 이슈타입 **id** (`10082`). 이름이 아니라 id다 — 같은 이름의 타입이 여럿일 수 있다.
 */
issueTypeId: string; summary: string; 
/**
 * ADF 문서. 프론트가 만들어 보낸다.
 */
description?: JsonValue | null; 
/**
 * createmeta가 요구한 나머지 필드. `{"reporter": {"id": "..."}}` 형태 그대로.
 */
extraFields?: Partial<{ [key in string]: JsonValue }> }
/**
 * 특정 프로젝트+이슈타입의 생성 폼 스키마.
 */
export type CreateMeta = { fields: CreateMetaField[] }
/**
 * createmeta가 알려주는 필드 하나 (DECISIONS 11.3).
 */
export type CreateMetaField = { 
/**
 * `summary`, `reporter`, `customfield_10011` …
 */
fieldId: string; name: string; required: boolean; 
/**
 * **`true`면 폼에 그리지 않는다.** 서버가 기본값을 채운다.
 */
hasDefaultValue: boolean; 
/**
 * `string` | `user` | `priority` | `array` | `option` …
 */
schemaType: string | null; 
/**
 * 드롭다운을 추가 API 호출 없이 채울 수 있다 (DECISIONS 11.3 "부수 발견").
 */
allowedValues: AllowedValue[] }
/**
 * 생성 성공 응답. Jira는 키/id/self만 돌려준다.
 */
export type CreatedIssue = { id: string; key: string; self?: string | null }
/**
 * 모달·폼에서 쓰는 단발 호출 실패.
 * 
 * [`JiraWidgetError`]와 나눠 둔 이유: 저쪽은 위젯 봉투라 `stale`(직전 성공 데이터)을
 * 들고 다닌다. 모달은 캐시하지 않으므로(D2) 그 필드가 늘 `None`이 되고,
 * 프론트가 "있을 수도 있는 값"을 매번 확인하게 만든다.
 */
export type JiraCallError = { 
/**
 * `transient` | `permanent` — 프론트가 [다시 시도]를 보일지 고르는 축.
 */
kind: string; 
/**
 * Jira 원문 그대로. 우리가 고쳐 쓰지 않는다.
 */
message: string; 
/**
 * 401. 전역 배너 1회 규칙의 트리거 (DECISIONS 16장).
 */
isAuthFailure: boolean; retryAfterSecs: number | null }
export type JiraComment = { id: string; author: JiraUser | null; created: string | null; updated: string | null; 
/**
 * ADF 본문. 설명과 동일하게 그대로 통과.
 */
body: JsonValue | null }
/**
 * 상세 모달의 코멘트 영역.
 */
export type JiraCommentsView = { 
/**
 * **시간 오름차순(대화 순서)으로 정렬된 최신 20건.**
 * 
 * Jira에 `orderBy=-created`로 요청해 최신 20건을 받고 여기서 뒤집는다.
 * 정렬 책임을 프론트에 넘기지 않는다 — 화면이 데이터를 재가공하기 시작하면
 * "Rust가 데이터의 주인"이라는 경계가 흐려진다.
 */
comments: JiraComment[]; total: number; 
/**
 * `total`이 받아온 개수보다 많은가. "이전 N개는 Jira에서" 링크를 띄울지.
 */
hasOlder: boolean }
/**
 * 연결 상태. 프론트가 알아야 할 것은 두 가지뿐이다 —
 * 설정이 됐는지, 그리고 티켓 링크를 만들 base URL이 무엇인지.
 * **토큰과 이메일은 넘기지 않는다.**
 */
export type JiraConnectionInfo = { configured: boolean; baseUrl: string | null }
/**
 * 생성 실패. [`JiraCallError`]에 "티켓이 생겼을 수도 있다"는 축이 더 붙는다.
 */
export type JiraCreateFailure = { kind: string; message: string; isAuthFailure: boolean; 
/**
 * 요청이 Jira에 닿았는지 알 수 없다 → 티켓이 만들어졌을 수 있다.
 * 
 * 프론트는 이때 [생성] 버튼을 잠그고 "Jira에서 확인하세요"를 띄운다.
 * 생성은 멱등이 아니고 우리에겐 삭제 기능이 없다.
 */
possiblyCreated: boolean; 
/**
 * 400 재조회 결과, 우리가 채울 수 없는 필수 필드.
 */
missingFields: CreateMetaField[]; 
/**
 * 자동 재시도를 실제로 했는가 (로그·표시용).
 */
retried: boolean }
/**
 * 생성 폼·설정창이 공유하는 프로젝트 목록.
 */
export type JiraCreateOptions = { projects: JiraProjectWithTypes[]; 
/**
 * ISO 8601. ↻ 버튼 옆의 "3일 전" 표시용.
 */
fetchedAt: string | null; 
/**
 * 디스크 캐시에서 온 것인가.
 */
fromCache: boolean }
/**
 * 설정창 "연결 테스트" 결과. `/myself` 응답에서 뽑는다.
 * 
 * `Deserialize`는 아래에 손으로 구현했다 (`avatarUrls` 맵 접기).
 */
export type JiraIdentity = { accountId: string; displayName?: string; 
/**
 * 사이트 개인정보 설정에 따라 숨겨질 수 있다. 없다고 실패가 아니다.
 */
emailAddress?: string | null; avatarUrl?: string | null }
/**
 * 목록 위젯 행 하나. **여기 필드를 늘리기 전에 [`LIST_FIELDS`]와 페이로드 크기를 생각할 것.**
 * 
 * `Deserialize`는 파일 아래쪽에 손으로 구현했다 — Jira의 `{key, fields:{...}}` 중첩을
 * 평평하게 펴고 `avatarUrls` 맵을 URL 하나로 접어야 하기 때문.
 */
export type JiraIssue = { 
/**
 * `PROJ-123`. 사용자에게 보이는 유일한 식별자이자 우리 캐시 키.
 */
key: string; summary: string; status: JiraStatus | null; 
/**
 * 담당자 없음은 흔하다. 백로그 티켓 대부분이 그렇다.
 */
assignee: JiraUser | null; 
/**
 * 우선순위 스킴을 끈 프로젝트에서는 null.
 */
priority: JiraPriority | null; issueType: JiraIssueType | null; 
/**
 * ISO 8601 + 오프셋 (`2026-07-29T14:03:11.482+0900`). 기본 정렬 축.
 */
updated: string | null; created: string | null; 
/**
 * `2026-07-27` (시각 없음). 실측 9/22만 채워져 있다.
 */
dueDate: string | null; parent: JiraParent | null; 
/**
 * 활성 스프린트 하나. 여러 개면 첫 번째.
 */
sprint: JiraSprint | null }
/**
 * 상세 모달용. 목록 필드 + 보고자·라벨·생성일·ADF 설명 (DECISIONS 11.4).
 */
export type JiraIssueDetail = { key: string; summary: string; status: JiraStatus | null; assignee: JiraUser | null; reporter: JiraUser | null; priority: JiraPriority | null; issueType: JiraIssueType | null; updated: string | null; created: string | null; 
/**
 * 라벨 없음은 `null`이 아니라 `[]`로 정규화한다 — 프론트 분기 하나를 없앤다.
 */
labels: string[]; 
/**
 * ADF 문서 그대로. 설명이 비어 있으면 `None`.
 */
description: JsonValue | null; 
/**
 * `2026-07-27` (시각 없음).
 */
dueDate: string | null; 
/**
 * 상위 항목. 모달 안에서 이 티켓으로 전환할 수 있다.
 */
parent: JiraParent | null; 
/**
 * 활성 스프린트 하나.
 */
sprint: JiraSprint | null }
export type JiraIssueType = { name: string; iconUrl?: string | null; subtask?: boolean }
/**
 * 생성 폼의 이슈타입 선택지. `/project/search?expand=issueTypes` 응답 항목.
 */
export type JiraIssueTypeOption = { id: string; name: string; description?: string | null; iconUrl?: string | null; 
/**
 * 하위작업 타입은 `parent`가 필수라 생성 폼에서 제외한다.
 */
subtask?: boolean; 
/**
 * -1 하위작업 / 0 표준 / 1 에픽. Jira가 주지 않으면 0으로 본다.
 */
hierarchyLevel?: number }
/**
 * 상위 항목. 팀 관리형에서는 에픽이고, 하위 작업이면 부모 티켓이다.
 * 
 * 구 `customfield_10014`(에픽 링크)는 쓰지 않는다 — 실측 결과 `parent`가
 * 20/22, 에픽 링크가 6/22로 `parent` 쪽이 훨씬 잘 채워져 있다.
 */
export type JiraParent = { key: string; summary?: string | null }
export type JiraPriority = { name: string; iconUrl?: string | null }
/**
 * 프로젝트 선택 드롭다운 한 항목.
 */
export type JiraProject = { 
/**
 * `ABC`. JQL에 그대로 들어가는 값이다.
 */
key: string; name: string }
/**
 * 프로젝트 + 그 프로젝트에서 만들 수 있는 이슈타입.
 * 
 * 실측(2026-07-31): `action=create`와 `action=view`가 같은 5개를 준다.
 * 그래서 목록 하나로 설정창(조회 범위)과 생성 폼을 모두 채운다.
 */
export type JiraProjectWithTypes = { key: string; name: string; issueTypes?: JiraIssueTypeOption[] }
/**
 * 위젯 config에 저장되는 쿼리. 프리셋이거나 생 JQL이거나 둘 중 하나.
 * 
 * 프리셋을 JQL 문자열로 굳혀 저장하지 않는 이유: 나중에 프리셋 정의를 고치면
 * 이미 배치된 위젯들도 같이 고쳐져야 한다. id로 저장하면 그게 공짜다.
 */
export type JiraQuery = 
/**
 * 프리셋 id. 알 수 없는 id면 [`JiraQuery::to_jql`]가 `None`을 준다.
 */
{ kind: "preset"; id: string } | 
/**
 * 탈출구. 사용자가 직접 쓴 JQL을 **그대로** 보낸다.
 * 
 * 검증하지 않는다 — 우리가 JQL 파서를 쓸 이유가 없고, 틀리면 Jira가
 * 훨씬 나은 에러 메시지를 준다 (DECISIONS 16장, 400은 원문 보존).
 */
{ kind: "raw"; jql: string }
/**
 * 스프린트 하나. Jira는 배열로 주지만(과거 스프린트 포함) 표시에는 활성 것 하나면 된다.
 */
export type JiraSprint = { name: string; 
/**
 * `active` | `closed` | `future`
 */
state?: string | null }
export type JiraStatus = { name: string; 
/**
 * 워크플로우가 이상하게 설정된 프로젝트에서 누락될 수 있다.
 */
statusCategory?: JiraStatusCategory | null }
/**
 * 상태 카테고리. 색을 칠하는 근거는 상태 **이름**이 아니라 이것이다.
 * 
 * 상태 이름은 프로젝트마다 다르다("완료"/"Done"/"배포됨"). `statusCategory.key`는
 * `new` / `indeterminate` / `done` 세 가지로 고정이라 위젯이 믿을 수 있는 유일한 축이다.
 */
export type JiraStatusCategory = { 
/**
 * `new` | `indeterminate` | `done` (Jira가 보장하는 고정 키)
 */
key: string; 
/**
 * `blue-gray` | `yellow` | `green` — 표시용 힌트
 */
colorName?: string | null; name?: string | null }
/**
 * 사용자. 식별자는 **`accountId`** — 이메일/username이 아니다 (GDPR 이후 Cloud 정책).
 */
export type JiraUser = { accountId: string; 
/**
 * 드물게 비어 있다(비활성/삭제된 계정). 그래도 항상 문자열은 온다.
 */
displayName?: string; 
/**
 * 48x48 아바타 URL. 아바타가 없는 계정이 실제로 있다.
 */
avatarUrl?: string | null }
export type JiraWidgetConfig = { 
/**
 * 사용자가 붙인 위젯 이름. 비어 있으면 쿼리 이름을 쓴다.
 */
title?: string | null; query: JiraQuery; 
/**
 * DECISIONS 11.2 — 기본 30건.
 */
maxResults: number; 
/**
 * 프로젝트 키로 범위를 좁힌다. 빈 목록이면 전체.
 * 
 * 쿼리와 분리해서 두는 이유: 프리셋이든 생 JQL이든 똑같이 적용돼야 한다.
 * 프리셋마다 프로젝트별 변종을 만드는 것은 조합 폭발이다.
 */
projects?: string[]; 
/**
 * 자동 새로고침 주기(초). **0이면 자동 갱신하지 않는다** — 수동 새로고침만.
 * 
 * 위젯마다 다르다(DECISIONS 11.2). 프론트에서 1분 미만으로 내려오지
 * 않도록 막지만, 손으로 고친 board.json에 대비해 여기서도 보정한다.
 */
refreshSecs?: number; 
/**
 * 목록에 표시할 열. 비어 있으면 기본 세트.
 */
columns?: string[] | null; 
/**
 * 정렬 기준. **프리셋에만 적용된다** — 생 JQL의 ORDER BY는 사용자 몫이다.
 */
sortField?: SortField | null; sortDirection?: SortDirection | null }
/**
 * 위젯 데이터 봉투. 프론트의 `WidgetEnvelope<T>`와 짝을 이룬다.
 * 
 * 로딩/에러 상태를 명시적으로 담는 이유: TanStack Query를 쓰지 않기로 했으므로
 * (DECISIONS 5장) 그것이 공짜로 주던 `isLoading`/`isError`를 직접 모델링해야 한다.
 */
export type JiraWidgetData = { issues: JiraIssue[]; 
/**
 * 실제로 네트워크에서 가져온 시각. 캐시 히트면 과거 시각이다 — "N분 전 데이터" 표시용.
 */
fetchedAt: string; 
/**
 * 이 응답이 디스크 캐시에서 왔는가. true면 갱신이 실패했거나 아직 안 끝났다는 뜻.
 */
fromCache: boolean }
export type JiraWidgetError = { 
/**
 * `transient` | `permanent` — 프론트가 재시도 UI를 고르는 축.
 */
kind: string; message: string; 
/**
 * 401 여부. 전역 배너를 한 번만 띄우기 위한 신호(DECISIONS 16장).
 */
isAuthFailure: boolean; retryAfterSecs: number | null; 
/**
 * 실패했지만 직전 성공 데이터가 있으면 함께 준다. 목록을 비우지 않기 위해서.
 */
stale: JiraWidgetData | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * 프리셋 정의. 정적 테이블이므로 `&'static str`.
 */
export type Preset = { 
/**
 * 저장되는 안정적 식별자. **한번 정하면 바꾸지 않는다** (기존 위젯이 깨진다).
 */
id: string; 
/**
 * 설정 UI에 보이는 이름.
 */
name: string; 
/**
 * 이 프리셋이 무엇을 보여주는지 한 줄 설명.
 */
description: string; jql: string }
export type SortDirection = "asc" | "desc"
/**
 * 프리셋에 적용할 정렬 기준.
 * 
 * **생 JQL에는 적용하지 않는다.** 사용자가 쓴 JQL에 이미 `ORDER BY`가 있으면
 * 우리가 덧붙일 수 없고, 없더라도 정렬은 그 JQL의 일부로 사용자가 정할 몫이다.
 */
export type SortField = "updated" | "created" | "due" | "priority" | "key"
export type TodoItem = { id: string; text: string; done: boolean; 
/**
 * The date this item currently sits on. Carry-over mutates this field.
 */
date: string; 
/**
 * The date it was first created. Never changes — it is what makes
 * "N일째" meaningful after several carries.
 */
originDate: string; 
/**
 * How many times this item has been carried forward.
 */
carriedCount: number }
/**
 * 되돌리기 결과. `restored`가 report의 개수보다 적을 수 있다 —
 * 이월 뒤에 사용자가 지우거나 옮긴 항목은 건드리지 않는다.
 */
export type UndoCarryResult = { items: TodoItem[]; restored: number }
export type Widget = { id: string; type: WidgetType; layout: WidgetLayout; 
/**
 * Type-specific settings — JQL, GitHub query, refresh interval, and so on.
 * 
 * Deliberately untyped. DECISIONS 4: 위젯 하나 = 프론트 폴더 하나 + Rust
 * provider 하나. If this module named every provider's config type, adding
 * a widget would mean editing storage, which is exactly the coupling the
 * decision forbids. Providers own their own shapes and parse this
 * themselves.
 */
config?: JsonValue }
/**
 * Grid position. DECISIONS 2: 12-column grid, so `x + w <= 12`.
 * 
 * Not enforced here — react-grid-layout owns collision and compaction, and a
 * store that rejected layouts RGL considers valid would fight it.
 */
export type WidgetLayout = { x: number; y: number; w: number; h: number }
/**
 * Widget type. DECISIONS 3 caps instances per type, not overall — Todo widgets
 * are free while Jira widgets cost API quota.
 */
export type WidgetType = "jira" | "github" | "todo" | 
/**
 * Spike: iframe widget. Without this variant `board_save` rejects the whole
 * board file, so a web widget would vanish on restart.
 */
"web"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
